drop table if exists CUSTOMER_DETAILS;
CREATE TABLE CUSTOMER_DETAILS(
CUST_ID INT NOT NULL,
TITLE	VARCHAR(5),
FIRST_NAME	VARCHAR(20),
LAST_NAME	VARCHAR(100),
DOB	VARCHAR(100),
GENDER	VARCHAR(1),
MARITAL_STATUS	VARCHAR(10),
NATIONALITY	VARCHAR(50),
ADDRESS_1	VARCHAR(100),
ADDRESS_2	VARCHAR(100),
ADDRESS_3	VARCHAR(100),
CITY	VARCHAR(20),
STATE	VARCHAR(20),
COUNTRY	VARCHAR(20),
PINCODE	INT,
HOME_NUMBER	INT,
PHONE_NUMBER	INT,
EMAIL_ID	VARCHAR(50)
);

drop table if exists FAMILY_DETAILS;
CREATE TABLE FAMILY_DETAILS(
CUST_ID INT NOT NULL,
S_ID INT NOT NULL AUTO_INCREMENT,	
S_FIRST_NAME	VARCHAR(20),
S_LAST_NAME	VARCHAR(20),
S_DOB	VARCHAR(15),
S_GENDER	VARCHAR(1),
S_NATIONALITY	VARCHAR(50),
S_MOBILE_NUMBER	INT,
S_EMAIL_ID	VARCHAR(50)
);

drop table if exists EMERGENCY_DETAILS;
CREATE TABLE EMERGENCY_DETAILS(	
CUST_ID INT NOT NULL,
E_ID INT NOT NULL AUTO_INCREMENT,
E_FIRST_NAME	VARCHAR(20),
E_LAST_NAME	VARCHAR(20),
E_MOBILE_NUMBER	INT,
E_RELATIONSHIP	VARCHAR(20)
);

INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (1, 'Mr','aaa','rrr','1/1/1990','M','married','indian','01-02','15','Bedok','Singapore','Singapore','Singapore',478933,12345678,'aaa.rrr@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (2, 'Mrs','bbb','sss','2/10/1990','F','unmarried','chinese','01-03','16','Pasir Panjang','Singapore','Singapore','Singapore',478934,12345679,'bbb.sss@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (3, 'Mr','ccc','ttt','3/7/1991','M','divorced','singaporean','01-04','17','Tampiness','Singapore','Singapore','Singapore',478935,12345680,'ccc.ttt@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (4, 'Mrs','ddd','uuu','2/4/1992','F','widowed','indonesian','01-05','18','Changi','Singapore','Singapore','Singapore',478936,12345681,'ddd.uuu@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (5, 'Mr','eee','vvv','1/1/1993','M','married','vietnamese','01-06','19','Harbour Front','Singapore','Singapore','Singapore',478937,12345682,'eee.vvv@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (6, 'Mrs','fff','www','2/10/1993','F','unmarried','indian','01-07','20','Bedok','Singapore','Singapore','Singapore',478938,12345683,'fff.www@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (7, 'Mr','ggg','xxx','3/7/1994','M','divorced','chinese','01-08','21','Pasir Panjang','Singapore','Singapore','Singapore',478939,12345684,'ggg.xxx@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (8, 'Mrs','hhh','yyy','3/4/1995','F','widowed','singaporean','01-09','22','Tampiness','Singapore','Singapore','Singapore',478940,12345685,'hhh.yyy@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (9, 'Mr','iii','zzz','2/1/1996','M','married','indonesian','01-10','23','Changi','Singapore','Singapore','Singapore',478941,12345686,'iii.zzz@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (10, 'Mrs','jjj','abc','2/10/1996','F','unmarried','vietnamese','01-11','24','Harbour Front','Singapore','Singapore','Singapore',478942,12345687,'jjj.abc@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (11, 'Mr','kkk','def','3/7/1997','M','divorced','indian','01-12','25','Bedok','Singapore','Singapore','Singapore',478943,12345688,'kkk.def@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (12, 'Mrs','lll','ghi','3/4/1998','F','widowed','chinese','01-13','26','Pasir Panjang','Singapore','Singapore','Singapore',478944,12345689,'lll.ghi@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (13, 'Mr','mmm','jkl','2/1/1999','M','married','singaporean','01-14','27','Tampiness','Singapore','Singapore','Singapore',478945,12345690,'mmm.jkl@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (14, 'Mrs','nnn','mno','3/10/1999','F','unmarried','indonesian','01-15','28','Changi','Singapore','Singapore','Singapore',478946,12345691,'nnn.mno@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (15, 'Mr','ooo','pqr','3/7/2000','M','divorced','vietnamese','01-16','29','Harbour Front','Singapore','Singapore','Singapore',478947,12345692,'ooo.pqr@gmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (16, 'Mrs','ppp','stu','3/4/2001','F','widowed','indian','01-17','30','Bedok','Singapore','Singapore','Singapore',478948,12345693,'ppp.stu@hotmail.com');
INSERT INTO CUSTOMER_DETAILS (CUST_ID, TITLE, FIRST_NAME, LAST_NAME, DOB, GENDER, MARITAL_STATUS, NATIONALITY, ADDRESS_1, ADDRESS_2, ADDRESS_3, CITY, STATE, COUNTRY, PINCODE, PHONE_NUMBER, EMAIL_ID) VALUES (17, 'Mr','qqq','vwx','2/1/2002','M','married','chinese','01-18','31','Pasir Panjang','Singapore','Singapore','Singapore',478949,12345694,'qqq.vwx@gmail.com');

INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (1, 'ab','rs','10/10/1989','F','chinese',11112222,'ab.rs@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (2, 'cd','tu','11/12/1991','M','singaporean',11112223,'cd.tu@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (3, 'ef','vw','10/2/1994','F','indonesian',11112224,'ef.vw@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (4, 'gh','xy','12/4/1996','M','vietnamese',11112225,'gh.xy@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (5, 'ij','za','13/6/1998','F','indian',11112226,'ij.za@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (6, 'kl','bc','13/8/1990','M','chinese','11112227','kl.bc@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (7, 'mn','de','14/10/1992','F','singaporean','11112228','mn.de@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (8, 'op','fg','14/12/1994','M','indonesian','11112229','op.fg@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (9, 'qr','hi','14/2/1997','F','vietnamese','11112230','qr.hi@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (10, 'st','jk','16/4/1999','M','indian','11112231','st.jk@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (11, 'uv','lm','17/6/1991','F','chinese','11112232','uv.lm@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (12, 'wx','no','17/8/1993','M','singaporean','11112233','wx.no@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (13, 'yz','pq','18/10/1995','F','indonesian','11112234','yz.pq@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (14, 'ac','rs','18/12/1997','M','vietnamese','11112235','ac.rs@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (15, 'bd','tu','18/2/1990','F','indian','11112236','bd.tu@gmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (16, 'eg','vw','20/4/1992','M','chinese','11112237','eg.vw@hotmail.com');
INSERT INTO FAMILY_DETAILS (CUST_ID, S_FIRST_NAME, S_LAST_NAME, S_DOB, S_GENDER, S_NATIONALITY, S_MOBILE_NUMBER, S_EMAIL_ID) VALUES (17, 'fh','xy','20/6/1994','F','singaporean','11112238','fh.xy@gmail.com');

INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (1, 'ddd','tu','99998888','friend');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (2, 'eee','vw','99998889','mother');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (3, 'fff','xy','99998890','father');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (4, 'ggg','za','99998891','sister');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (5, 'hhh','bc','99998892','brother');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (6, 'iii','de','99998893','friend');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (7, 'jjj','fg','99998894','mother');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (8, 'kkk','hi','99998895','father');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (9, 'lll','jk','99998896','sister');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (10, 'mmm','lm','99998897','brother');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (11, 'nnn','no','99998898','friend');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (12, 'ooo','pq','99998899','mother');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (13, 'ppp','rs','99998900','father');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (14, 'qqq','tu','99998901','sister');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (15, 'aaa','vw','99998902','brother');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (16, 'bbb','xy','99998903','friend');
INSERT INTO EMERGENCY_DETAILS (CUST_ID, E_FIRST_NAME, E_LAST_NAME, E_MOBILE_NUMBER, E_RELATIONSHIP) VALUES (17, 'ccc','rs','99998904','mother');
commit;